### ISSUE TITLE
list.json  404 ？

### ISSUE THREAD

**Issue by renhuan** [lowlighter/splatoon#1]
list.json  404 ？

**Comment by lowlighter** [comment]
Hi ! 

Sorry I forgot to put it in the readme but if you're deploying your own instance on vercel, you need these settings:

**Build command**: deno run -A build/mod.ts || /vercel/.deno/bin/deno run -A build/mod.ts
**Output directory**: .
**Install command**: curl -fsSL https://deno.land/x/install/install.sh | sh
