### ISSUE TITLE
v4.0 items

### ISSUE THREAD

**Issue by SirJorb** [lowlighter/splatoon#10]
Looks like items from v4.0/Sizzle Season 2023 are missing. Inkipedia lists Barrelfish Home Helmet, Cap'n Cap, Commander Cap, Crust Bucket Visor, Do-Rag, Cap & Glasses, Glam Clam Specs, Noise Cancelers, Seashell Bamboo Hat, See-an-Enemy HUD, and Stealth Squidbeak Shield, though I don't know if that's exhaustive.

**Comment by lowlighter** [comment]
Done as part of 
- #12
