### ISSUE TITLE
Match in-game Equip screen ordering

### ISSUE THREAD

**Issue by Tredenix** [lowlighter/splatoon#6]
Adjusting the order of brands and abilities at the top of the page, so that they match with the order on the Equip screen when pressing the L stick, would make marking off a full set of gear much smoother than it is currently.

![image](https://user-images.githubusercontent.com/107756522/221046971-4b39c4dd-bfd2-4548-a2a9-f44dbeb43267.png)

Also, by any chance could the Gear sort option could place Headgear above Clothing?

**Comment by lowlighter** [comment]
Hi 👋 !

All of these should be fixed now 😄 !
Thanks for suggesting it !
